---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-secret-k8s-operator
  labels:
    app: secure-secret-k8s-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: secure-secret-k8s-operator
  template:
    metadata:
      labels:
        app: secure-secret-k8s-operator
    spec:
      serviceAccountName: secure-secret-k8s-operator
      containers:
      - name: secure-secret-k8s-operator
        image: sunnyredhu/secure-secret-k8s-operator:latest
        # command: [ "/bin/sh", "-c", "--" ]
        # args: [ "sleep 1h" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secure-secret-k8s-operator
rules:
- apiGroups: ["stable.redhu.com"]
  resources: ["securesecrets"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secure-secret-k8s-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secure-secret-k8s-operator
subjects:
- kind: ServiceAccount
  name: secure-secret-k8s-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: secure-secret-k8s-operator
  apiGroup: rbac.authorization.k8s.io
