---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: securesecrets.stable.redhu.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: stable.redhu.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                secretType:
                  type: string
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                      value:
                        type: string
                    required: ["key", "value"]
                decryptionKeyName:
                  type: string
              required: ["secretType", "data", "decryptionKeyName"]
          required: ["spec"]
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: securesecrets
    # singular name to be used as an alias on the CLI and for display
    singular: securesecret
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: SecureSecret
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - ss
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-secret-k8s-operator
  labels:
    app: secure-secret-k8s-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: secure-secret-k8s-operator
  template:
    metadata:
      labels:
        app: secure-secret-k8s-operator
    spec:
      serviceAccountName: secure-secret-k8s-operator
      containers:
      - name: secure-secret-k8s-operator
        image: sunnyredhu/secure-secret-k8s-operator:latest
        # command: [ "/bin/sh", "-c", "--" ]
        # args: [ "sleep 1h" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secure-secret-k8s-operator
rules:
- apiGroups: ["stable.redhu.com"]
  resources: ["securesecrets"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secure-secret-k8s-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secure-secret-k8s-operator
subjects:
- kind: ServiceAccount
  name: secure-secret-k8s-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: secure-secret-k8s-operator
  apiGroup: rbac.authorization.k8s.io
